### ISSUE TITLE
DPS5005 v2.3 Voltage Offset

### ISSUE THREAD

**Issue by serialx** [kanflo/opendps#104] opened 2019-01-15 14:39 UTC
First, awesome project! Thank you! :)

I've upgraded my DPS5005 to OpenDPS according to the blog post. I'm seeing some voltage difference between what I set and what actually delivers.

DPS5005 Version (in the silkscreen): V2.3
CV Voltage set: 5.00 V
DPS5005 display shows: 4.73 V
My multimeter shows: 4.673 V

What could be the problem?

Dump of peripheral settings before reflash:

[4V-off.txt](https://github.com/kanflo/opendps/files/2760044/4V-off.txt)
[4V-on.txt](https://github.com/kanflo/opendps/files/2760045/4V-on.txt)
[5V-off.txt](https://github.com/kanflo/opendps/files/2760046/5V-off.txt)
[5V-on.txt](https://github.com/kanflo/opendps/files/2760047/5V-on.txt)

**Comment by Xenoamor** [comment] 2019-01-15 16:45
We're currently working on this for #17

**Comment by kanflo** [comment] 2019-01-15 20:24
First, thank _you_ :)

I will mark this as a duplicate of #17.

**Closed** 2019-01-15 20:25 UTC
Labels: duplicate
